import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import Link from 'next/link';
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] });


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar/>
        
        <section className='container mx-auto mt-4'>
          <div className='d-flex '>
          <div className='col-md-6 mt-4 '>
            <h2 className='text-dark display-4 fw-bold'> <span className='text-danger'>The total care</span> your child deserves</h2>
            <p className='text-dark pe-5 mb-3 fs-5'>Join thousands of happy families in giving your child the 
gift of ACH therapy and autism services.</p>
            <form className='row g-4' action="">
            <div className='col-md-5'>
              <input className='form-control' type="text" placeholder='Your Name' />
            </div>
            <div className='col-md-5'>
              <input className='form-control' type="email" placeholder='Your Email' />
            </div>
            <div className='col-md-5'>
              <input className='form-control' type="number" placeholder='Your Phone Number' />
            </div>
            <div className='col-md-5'>
              <input className='form-control' type="text" placeholder='Your Address' />
            </div>
            <div className='col-md-10'>
              <button className='btn btn-danger form-control py-2 shadow-sm'>
                Get Started Today <FontAwesomeIcon width={15} icon={faArrowRight} />
              </button>
            </div>
            
            </form>
           <div className='my-3 d-flex'>
            <div >
            <img width={20} src="./icon1.svg" alt="" />
            </div>
            <div>
            <p className='fw-bold ms-2'>we dedicate our lives to <span className='text-danger'>helping families.</span></p>
            </div>
           </div>
          </div>

          <div className='col-md-6 d-flex'>
          <div className='col-3'>
            <img width={125} src="./babe.png" alt="" />
          </div>
          <div className='col-3'>
            <img width={125} src="./babe1.png" alt="" />
          </div>
          <div className='col-5'>
            <img width={290} src="./babe2.png" alt="" />
          </div>
          </div>
          </div>
          

        </section>

        <section className='container mx-auto mt-3 d-flex'>
          <div className='col-3'>
            <p className='fw-bold'>Most insurance accepted</p>
          </div>

          <div className={`${styles.con} `}>
          <div className = {`${styles.slider} `} >
            <div className={`${styles.slide} `}>
            <img className= {styles.img} src="./slider1.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider2.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider3.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider4.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img className= {styles.img} src="./slider1.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider2.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider3.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./slider4.svg" alt="" />
            </div>
          </div>
          </div>
        </section>

        <section className={`container bg-danger bg-gradient p-5 border my-5 mx-auto rounded-4 shadow-sm ${styles.background}`}>
          <p className='text-light '>Our Vision</p>
          <h2 className='text-light'>Who We Are</h2>
          <p className='text-light col-9'>Our team of highly skilled therapists are passionate about their work and take great pride in seeing 
each child succeed. Our mission is to provide the highest level of care for your child. We dedicate our
lives to helping families with a child on the austism spectrum reach new heights.</p>


<div className='row mt-5'>
          <div className='col-4 text-light'>
              <img src="/about2.svg" alt="" />
              <p className='fw-bold mt-2 fs-4'>Our Mission</p>
              <p className='col-11'>Our mission is to help children grow and thrive by improving communication, social and adoptive skills. </p>
             <div className=''>
             <h5><Link className="fs-6 text-light fw-normal text-decoration-none" href={"/"}>learn more <FontAwesomeIcon width={12} icon={faArrowRight} /></Link></h5>
             </div>
          </div>
          <div className='col-4 text-light'>
              <img src="/about3.svg" alt="" />
              <p className='fw-bold mt-2 fs-4'>Our Vision</p>
              <p className='col-11'>We believe that children with autism can live happy and productive lives that are not defined by their specific needs.</p>
             <h5><Link className="fs-6 text-light fw-normal text-decoration-none" href={"/"}>learn more <FontAwesomeIcon width={12} icon={faArrowRight} /></Link></h5>
          </div>
          <div className='col-4 text-light'>
              <img src="/about1.svg" alt="" />
              <p className='fw-bold mt-2 fs-4'>Our Team</p>
              <p className='col-11'>Our dedicated and experience team developed programmes that suit each child’s unique skill set.</p>
             <h5><Link className="fs-6 text-light fw-normal text-decoration-none" href={"/"}>learn more <FontAwesomeIcon width={12} icon={faArrowRight} /></Link></h5>
          </div>
        </div>
        </section>

        <section className={`d-flex container p-5 my-5 mx-auto ${styles.background}`}>
          <div className={` col-md-6 align-items-center justify-content-center`}>
            <img className= {styles.babyfloat} src="/baby1.svg" alt="" />
          <div className={styles.shadow}>
            <img width={520}  src="/shadow-image.svg" alt="" />
          </div>
          </div>

          <div className="text-dark mt-3">
            <h1 className="fw-bold mb-4">How <span className="text-danger">ACH Therapy</span> Works</h1>
            <div className='d-flex mb-3'>
              <div className='me-3'><img src="/group3.svg" alt="" /></div>
              <div>
              <h4 className='fw-bold'>Getting to Know child</h4>
              <p>Our team of pyschologists spend time evaluating your child’s history and concerns. Our personal care team reviews this before the first meeting.</p>
              </div>
            </div>
            <div className='d-flex mb-3'>
              <div className='me-3'><img src="/group2.svg" alt="" /></div>
              <div>
              <h4 className='fw-bold'>Comprehensive evaluations</h4>
              <p>Our team of pyschologists complete comprehensive evaluations to make an accurate diagnosis of your child’s behavior.</p>
              </div>
            </div>
            <div className='d-flex mb-3'>
              <div className='me-3'><img src="/group4.svg" alt="" /></div>
              <div>
              <h4 className='fw-bold'>Custom care plan</h4>
              <p>Our team of professionals will develop a custom care plan tailored to your child’s needs and diagnosis.</p>
              </div>
            </div>
            <div className='col-md-5 ms-5'>
              <button className='btn btn-danger form-control py-2 shadow-sm rounded-4'>
                Get Started Today <FontAwesomeIcon width={15} icon={faArrowRight} />
              </button>
            </div>
          </div>
          
        </section>

        <section className={`${styles.contain} container-fluid`}>

            <div>
            <p className={`${styles.text} mb-2`}>What We Do</p>
            </div>

            <div className='row g-5 mt-2'>
            <div className='col-md-4'>
              <img width={40} src="/vector1.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>Benefit Checks</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex.</p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            <div className='col-md-4'>
              <img width={40} src="/vector2.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>Consultations</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex. </p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            <div className='col-md-4'>
              <img width={40} src="/vector3.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>Family Support</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex. </p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            <div className='col-md-4'>
              <img width={40} src="/vector4.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>Center-Based ACH Therapy</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex. </p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            <div className='col-md-4'>
              <img width={40} src="/vector5.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>At-home ACH Therapy</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex. </p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            <div className='col-md-4'>
              <img width={40} src="/vector6.svg" alt="" />
              <p className={`${styles.heading} mt-2`}>In-School ACH Therapy</p>
              <p className='text-dark'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam beatae minus commodi quasi illum cumque illo nisi perspiciatis, magnam reprehenderit tempora ex. </p>

              <h5><Link className={styles.link} href={"/"}>learn more</Link></h5>
            </div>
            </div>

        </section>

        <section className={`container p-5 my-5 mx-auto rounded-3 ${styles.newBackground}`}>
            <div className={`d-flex justify-content-around p-5 mx-auto rounded-4  ${styles.newbg}`}>
                <div className='col-md-3'>
                  <p className='fs-5 text-light'>Insurance We Accept</p>
                  <div className='col-md-6 mt-5'>
                  <button className='btn text-light form-control shadow-sm rounded-4'>
                Get Started
              </button>
                  </div>
                </div>

                <div className='col-md-7'>
                  <p className='text-light fs-6 col-8'>We Partner with most major insurance, enabling you to access premier therapy services.</p>
                  <div className={`${styles.space} mt-5`}>
          <div className = {`${styles.slider}`} >
            <div className={`${styles.slide} `}>
            <img className= {styles.img} src="./idol1.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol2.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol3.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol4.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img className= {styles.img} src="./idol1.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol2.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol3.svg" alt="" />
            </div>
            <div className={`${styles.slide} `}>
            <img src="./idol4.svg" alt="" />
            </div>
          </div>
          </div>
                </div>
            </div>
        </section>

        <section className={`${styles.section1} p-5 mx-auto`}>
          <h1 className='text-center fw-bold display-6 my-3'>Frequently asked Questions</h1>

          <div className='mx-auto d-flex justify-content-around p-5'>
          <div className='col-5'>
          <div className="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      What is ACH?
      </button>
    </h2>
    <div id="collapseOne" className="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
          </div>
          
          <div className='col-5'>
          <div className="accordion" id="accordionExample">
  <div className="accordion-item">
    <h2 className="accordion-header">
      <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      What is ACH?
      </button>
    </h2>
    <div id="collapseOne" className="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
          </div>

          </div>

        </section>
        <Footer/>
      </main>
    </>
  )
}
